import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import StoreProvider from "@/app/StoreProvider";

//import
import { readFileSync } from "fs";
import path from "path";
import { makeStore } from "@/lib/store";
import { setDesignToken } from "@/lib/features/designToken/designTokenSlice";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getDesignToken() {
  const filepath = path.join(process.cwd(), "public", "token.json");
  const fileContents = readFileSync(filepath, "utf8");
  return JSON.parse(fileContents);
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const test = await loadDesignToken();
  const tokens = await getDesignToken();
  const store = makeStore();
  store.dispatch(setDesignToken({ tokens }));

  const settingTokenIntoHTML = `
    :root {
      --color-primary: ${tokens.colors.primary};
      --color-secondary: ${tokens.colors.secondary};
      --font-base: ${tokens.sizes.fontBase};
      --padding: ${tokens.sizes.padding};
  }
`;
  return (
    <html lang="en">
      <head>
        <style>{settingTokenIntoHTML}</style>
      </head>
      <body className={inter.className}>
        <StoreProvider count={0}>{children}</StoreProvider>
      </body>
    </html>
  );
}
