import type { Metadata } from "next";
import { Inter } from "next/font/google";

//Redux
import { RootState } from "@/lib/store";
import { initializeStoreWithTokens } from "@/lib/initializeStoreWithTokens";
import StoreProvider from "@/app/StoreProvider";

import "./globals.css";
import StyledComponentsRegistry from "@/lib/styled-component/registry";

// for font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = await initializeStoreWithTokens();
  const tokens = store.getState().designToken.tokens;
  const settingTokenIntoHTML = `
    :root {
      --color-primary: ${tokens.colors.primary};
      --color-secondary: ${tokens.colors.secondary};
      --font-base: ${tokens.sizes.fontBase};
      --padding: ${tokens.sizes.padding};
  }
`;
  return (
    <html lang="en">
      <head>
        <style>{settingTokenIntoHTML}</style>
      </head>
      <body className={inter.className}>
        <StoreProvider initialState={store.getState() as RootState}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </StoreProvider>
      </body>
    </html>
  );
}
